# written by PropertiesConfiguration
# Tue Mar 03 13:53:29 VUT 2026

DEFAULT_PASS_LEN = 4
fullscreen_mode = false
show_db_configuration = true
use_translated_name = false
TOUCH_BUTTON_HEIGHT = 80
menu_button_width = 80
menu_button_height = 80
TOUCH_FONT_SIZE = 12
SCREEN_COMPONENT_SIZE_RATIO = 1.0
AUTO_LOGOFF_ENABLE = true
AUTO_LOGOFF_TIME = 600000
UseSettlementPrompt = false
show_barcode_on_receipt = false
group_kitchen_items_on_receipt = false
enable_multi_currency = false
AllowToDeletePrintedTicketItem = true
quick_maintenance = true
drawerPortName = COM1
controlCode = 27
active_customer_display = false
customerDisplayPort = COM2
customerDisplayMessage = 12345678912345678912
active_scale_display = false
scaleDisplayPort = COM3
scaleDisplayMessage = 1234
caller_id_device = NONE
active_caller_id_device = false
bwwidth = 1040
bwheight = 736
bwx = 724
bwy = 494
database_provider_name = POSTGRES
connection_string = jdbc:postgresql://localhost:5432/pos01wnf
database_url = localhost
database_port = 5432
database_name = pos01wnf
database_user = liam
database_pass = Knight@113078
default_view = RETAIL
terminal_id = 270
wwidth = 1390
wheight = 1007
wlocx = 3110
wlocy = 389
extendedstate = 0
