# written by PropertiesConfiguration
# Wed Mar 11 16:26:52 VUT 2026

defaultLocal = en
database_provider_name = POSTGRES
connection_string = jdbc:postgresql://localhost:5432/pos01wnf
database_url = localhost
database_port = 5432
database_name = pos01wnf
database_user = liam
database_pass = Knight@113078
terminal_id = 4862
default_view = ORDERS
bwwidth = 900
bwheight = 650
bwx = 1144
bwy = 638
wwidth = 1024
wheight = 724
wlocx = 754
wlocy = 437
extendedstate = 0
