/*
 * Generated by JasperReports - 1/26/26 10:11 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class TicketReceiptReport_1769425886690_563766 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_totalText = null;
    private JRFillParameter parameter_discountAmount = null;
    private JRFillParameter parameter_deliveryCharge = null;
    private JRFillParameter parameter_subtotalHeaderText = null;
    private JRFillParameter parameter_changeAmountText = null;
    private JRFillParameter parameter_adjustAmountText = null;
    private JRFillParameter parameter_serviceCharge = null;
    private JRFillParameter parameter_reportDate = null;
    private JRFillParameter parameter_tipsText = null;
    private JRFillParameter parameter_deliveryChargeText = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_copyType = null;
    private JRFillParameter parameter_tenderedAmount = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_cardInformation = null;
    private JRFillParameter parameter_barcode = null;
    private JRFillParameter parameter_receiptType = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_showSignatureField = null;
    private JRFillParameter parameter_ticketHeader = null;
    private JRFillParameter parameter_adjustAmount = null;
    private JRFillParameter parameter_totalAmountText = null;
    private JRFillParameter parameter_headerLine5 = null;
    private JRFillParameter parameter_totalAmount = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_headerLine1 = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_headerLine2 = null;
    private JRFillParameter parameter_headerLine3 = null;
    private JRFillParameter parameter_showHeaderSeparator = null;
    private JRFillParameter parameter_headerLine4 = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_additionalProperties = null;
    private JRFillParameter parameter_taxAmount = null;
    private JRFillParameter parameter_quantityText = null;
    private JRFillParameter parameter_paidAmount = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_dueAmountText = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_showSubtotal = null;
    private JRFillParameter parameter_subTotalText = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_serverName = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_showFooter = null;
    private JRFillParameter parameter_discountText = null;
    private JRFillParameter parameter_itemText = null;
    private JRFillParameter parameter_tenderedAmountText = null;
    private JRFillParameter parameter_paidAmountText = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_changedAmount = null;
    private JRFillParameter parameter_checkNo = null;
    private JRFillParameter parameter_serviceChargeText = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillParameter parameter_cardPayment = null;
    private JRFillParameter parameter_tableNo = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_taxText = null;
    private JRFillParameter parameter_tipAmount = null;
    private JRFillParameter parameter_netAmount = null;
    private JRFillParameter parameter_currencySymbol = null;
    private JRFillParameter parameter_terminal = null;
    private JRFillParameter parameter_subtotalAmount = null;
    private JRFillParameter parameter_dueAmount = null;
    private JRFillParameter parameter_footerMessage = null;
    private JRFillParameter parameter_guestCount = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_itemSubtotal = null;
    private JRFillField field_itemQty = null;
    private JRFillField field_itemName = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_totalText = (JRFillParameter)pm.get("totalText");
        parameter_discountAmount = (JRFillParameter)pm.get("discountAmount");
        parameter_deliveryCharge = (JRFillParameter)pm.get("deliveryCharge");
        parameter_subtotalHeaderText = (JRFillParameter)pm.get("subtotalHeaderText");
        parameter_changeAmountText = (JRFillParameter)pm.get("changeAmountText");
        parameter_adjustAmountText = (JRFillParameter)pm.get("adjustAmountText");
        parameter_serviceCharge = (JRFillParameter)pm.get("serviceCharge");
        parameter_reportDate = (JRFillParameter)pm.get("reportDate");
        parameter_tipsText = (JRFillParameter)pm.get("tipsText");
        parameter_deliveryChargeText = (JRFillParameter)pm.get("deliveryChargeText");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_copyType = (JRFillParameter)pm.get("copyType");
        parameter_tenderedAmount = (JRFillParameter)pm.get("tenderedAmount");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_cardInformation = (JRFillParameter)pm.get("cardInformation");
        parameter_barcode = (JRFillParameter)pm.get("barcode");
        parameter_receiptType = (JRFillParameter)pm.get("receiptType");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_showSignatureField = (JRFillParameter)pm.get("showSignatureField");
        parameter_ticketHeader = (JRFillParameter)pm.get("ticketHeader");
        parameter_adjustAmount = (JRFillParameter)pm.get("adjustAmount");
        parameter_totalAmountText = (JRFillParameter)pm.get("totalAmountText");
        parameter_headerLine5 = (JRFillParameter)pm.get("headerLine5");
        parameter_totalAmount = (JRFillParameter)pm.get("totalAmount");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_headerLine1 = (JRFillParameter)pm.get("headerLine1");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_headerLine2 = (JRFillParameter)pm.get("headerLine2");
        parameter_headerLine3 = (JRFillParameter)pm.get("headerLine3");
        parameter_showHeaderSeparator = (JRFillParameter)pm.get("showHeaderSeparator");
        parameter_headerLine4 = (JRFillParameter)pm.get("headerLine4");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_additionalProperties = (JRFillParameter)pm.get("additionalProperties");
        parameter_taxAmount = (JRFillParameter)pm.get("taxAmount");
        parameter_quantityText = (JRFillParameter)pm.get("quantityText");
        parameter_paidAmount = (JRFillParameter)pm.get("paidAmount");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_dueAmountText = (JRFillParameter)pm.get("dueAmountText");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_showSubtotal = (JRFillParameter)pm.get("showSubtotal");
        parameter_subTotalText = (JRFillParameter)pm.get("subTotalText");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_serverName = (JRFillParameter)pm.get("serverName");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_showFooter = (JRFillParameter)pm.get("showFooter");
        parameter_discountText = (JRFillParameter)pm.get("discountText");
        parameter_itemText = (JRFillParameter)pm.get("itemText");
        parameter_tenderedAmountText = (JRFillParameter)pm.get("tenderedAmountText");
        parameter_paidAmountText = (JRFillParameter)pm.get("paidAmountText");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_changedAmount = (JRFillParameter)pm.get("changedAmount");
        parameter_checkNo = (JRFillParameter)pm.get("checkNo");
        parameter_serviceChargeText = (JRFillParameter)pm.get("serviceChargeText");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
        parameter_cardPayment = (JRFillParameter)pm.get("cardPayment");
        parameter_tableNo = (JRFillParameter)pm.get("tableNo");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_taxText = (JRFillParameter)pm.get("taxText");
        parameter_tipAmount = (JRFillParameter)pm.get("tipAmount");
        parameter_netAmount = (JRFillParameter)pm.get("netAmount");
        parameter_currencySymbol = (JRFillParameter)pm.get("currencySymbol");
        parameter_terminal = (JRFillParameter)pm.get("terminal");
        parameter_subtotalAmount = (JRFillParameter)pm.get("subtotalAmount");
        parameter_dueAmount = (JRFillParameter)pm.get("dueAmount");
        parameter_footerMessage = (JRFillParameter)pm.get("footerMessage");
        parameter_guestCount = (JRFillParameter)pm.get("guestCount");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_itemSubtotal = (JRFillField)fm.get("itemSubtotal");
        field_itemQty = (JRFillField)fm.get("itemQty");
        field_itemName = (JRFillField)fm.get("itemName");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Boolean)(true); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showHeaderSeparator.getValue())!=null && ((java.lang.Boolean)parameter_showHeaderSeparator.getValue())==true); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_itemText.getValue())); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_quantityText.getValue())); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showSubtotal.getValue())==true); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subtotalHeaderText.getValue())); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_receiptType.getValue())); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ticketHeader.getValue())); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_barcode.getValue())); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Boolean)(Boolean.valueOf(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getValue())).equals("1"))); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemName.getValue())); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showSubtotal.getValue())==true); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemSubtotal.getValue())); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemQty.getValue())); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tipAmount.getValue())!=null); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tipsText.getValue())); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subTotalText.getValue())); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalAmountText.getValue())); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_dueAmountText.getValue())!=null); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_dueAmount.getValue())); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_taxAmount.getValue())!=null); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_taxText.getValue())); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subtotalAmount.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalAmount.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_taxAmount.getValue())); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_dueAmountText.getValue())!=null); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_dueAmountText.getValue())); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tipAmount.getValue())); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_paidAmount.getValue())); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_paidAmountText.getValue())); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_serviceCharge.getValue())!=null); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_serviceChargeText.getValue())); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_serviceCharge.getValue())); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_discountAmount.getValue())!=null); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_discountText.getValue())); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_discountAmount.getValue())); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_footerMessage.getValue())); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_deliveryCharge.getValue())!=null); //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_deliveryChargeText.getValue())); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_deliveryCharge.getValue())); //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_changedAmount.getValue()) != null); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_changeAmountText.getValue())); //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_changedAmount.getValue())); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_additionalProperties.getValue())); //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_cardInformation.getValue())); //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_copyType.getValue())); //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_adjustAmount.getValue())!=null); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_adjustAmountText.getValue())); //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_adjustAmount.getValue())); //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tenderedAmount.getValue())!=null); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tenderedAmount.getValue())); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tenderedAmount.getValue())!=null); //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tenderedAmountText.getValue())); //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true && ((java.lang.Boolean)parameter_showSignatureField.getValue())); //$JR_EXPR_ID=83$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Boolean)(true); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showHeaderSeparator.getValue())!=null && ((java.lang.Boolean)parameter_showHeaderSeparator.getValue())==true); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_itemText.getValue())); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_quantityText.getValue())); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showSubtotal.getValue())==true); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subtotalHeaderText.getValue())); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_receiptType.getValue())); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ticketHeader.getValue())); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_barcode.getValue())); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Boolean)(Boolean.valueOf(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())).equals("1"))); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemName.getOldValue())); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showSubtotal.getValue())==true); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemSubtotal.getOldValue())); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemQty.getOldValue())); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tipAmount.getValue())!=null); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tipsText.getValue())); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subTotalText.getValue())); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalAmountText.getValue())); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_dueAmountText.getValue())!=null); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_dueAmount.getValue())); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_taxAmount.getValue())!=null); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_taxText.getValue())); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subtotalAmount.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalAmount.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_taxAmount.getValue())); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_dueAmountText.getValue())!=null); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_dueAmountText.getValue())); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tipAmount.getValue())); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_paidAmount.getValue())); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_paidAmountText.getValue())); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_serviceCharge.getValue())!=null); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_serviceChargeText.getValue())); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_serviceCharge.getValue())); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_discountAmount.getValue())!=null); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_discountText.getValue())); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_discountAmount.getValue())); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_footerMessage.getValue())); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_deliveryCharge.getValue())!=null); //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_deliveryChargeText.getValue())); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_deliveryCharge.getValue())); //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_changedAmount.getValue()) != null); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_changeAmountText.getValue())); //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_changedAmount.getValue())); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_additionalProperties.getValue())); //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_cardInformation.getValue())); //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_copyType.getValue())); //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_adjustAmount.getValue())!=null); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_adjustAmountText.getValue())); //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_adjustAmount.getValue())); //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tenderedAmount.getValue())!=null); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tenderedAmount.getValue())); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tenderedAmount.getValue())!=null); //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tenderedAmountText.getValue())); //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true && ((java.lang.Boolean)parameter_showSignatureField.getValue())); //$JR_EXPR_ID=83$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Boolean)(true); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(1)); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new java.lang.Integer(0)); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine1.getValue())); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine2.getValue())); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine3.getValue())); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine4.getValue())); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_headerLine5.getValue())); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showHeaderSeparator.getValue())!=null && ((java.lang.Boolean)parameter_showHeaderSeparator.getValue())==true); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_itemText.getValue())); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_quantityText.getValue())); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showSubtotal.getValue())==true); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subtotalHeaderText.getValue())); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_receiptType.getValue())); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ticketHeader.getValue())); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_barcode.getValue())); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Boolean)(Boolean.valueOf(String.valueOf(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())).equals("1"))); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemName.getValue())); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showSubtotal.getValue())==true); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemSubtotal.getValue())); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)field_itemQty.getValue())); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tipAmount.getValue())!=null); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tipsText.getValue())); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subTotalText.getValue())); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalAmountText.getValue())); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_dueAmountText.getValue())!=null); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_dueAmount.getValue())); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_taxAmount.getValue())!=null); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_taxText.getValue())); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_subtotalAmount.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalAmount.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_taxAmount.getValue())); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_dueAmountText.getValue())!=null); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_dueAmountText.getValue())); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tipAmount.getValue())); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_paidAmount.getValue())); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_paidAmountText.getValue())); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_serviceCharge.getValue())!=null); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_serviceChargeText.getValue())); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_serviceCharge.getValue())); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_discountAmount.getValue())!=null); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_discountText.getValue())); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_discountAmount.getValue())); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_showFooter.getValue())==true); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_footerMessage.getValue())); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_deliveryCharge.getValue())!=null); //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_deliveryChargeText.getValue())); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_deliveryCharge.getValue())); //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_changedAmount.getValue()) != null); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_changeAmountText.getValue())); //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_changedAmount.getValue())); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_additionalProperties.getValue())); //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_cardInformation.getValue())); //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_copyType.getValue())); //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true); //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_adjustAmount.getValue())!=null); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_adjustAmountText.getValue())); //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_adjustAmount.getValue())); //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tenderedAmount.getValue())!=null); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tenderedAmount.getValue())); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.lang.Boolean)(((java.lang.String)parameter_tenderedAmount.getValue())!=null); //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_tenderedAmountText.getValue())); //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)parameter_cardPayment.getValue())==true && ((java.lang.Boolean)parameter_showSignatureField.getValue())); //$JR_EXPR_ID=83$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
