-- Timestamp: 2025-12-05 07:39:25.257
-- Source database is: /tmp/derby-posdb-migration
-- Connection URL is: jdbc:derby:/tmp/derby-posdb-migration
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."SHOP_TABLE" ("ID" INTEGER NOT NULL, "NAME" VARCHAR(20), "DESCRIPTION" VARCHAR(60), "CAPACITY" INTEGER, "X" INTEGER, "Y" INTEGER, "FREE" SMALLINT, "SERVING" SMALLINT, "BOOKED" SMALLINT, "DIRTY" SMALLINT, "DISABLE" SMALLINT, "FLOOR_ID" INTEGER);

CREATE TABLE "APP"."USERS" ("AUTO_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "USER_ID" INTEGER, "USER_PASS" VARCHAR(16) NOT NULL, "FIRST_NAME" VARCHAR(30), "LAST_NAME" VARCHAR(30), "SSN" VARCHAR(30), "COST_PER_HOUR" DOUBLE, "CLOCKED_IN" SMALLINT, "LAST_CLOCK_IN_TIME" TIMESTAMP, "LAST_CLOCK_OUT_TIME" TIMESTAMP, "PHONE_NO" VARCHAR(20), "IS_DRIVER" SMALLINT, "AVAILABLE_FOR_DELIVERY" SMALLINT, "ACTIVE" SMALLINT, "SHIFT_ID" INTEGER, "CURRENTTERMINAL" INTEGER, "N_USER_TYPE" INTEGER);

CREATE TABLE "APP"."MENU_ITEM_PROPERTIES" ("MENU_ITEM_ID" INTEGER NOT NULL, "PROPERTY_VALUE" VARCHAR(100), "PROPERTY_NAME" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."SHOP_FLOOR" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60), "OCCUPIED" SMALLINT, "IMAGE" BLOB(5242880));

CREATE TABLE "APP"."TERMINAL_PRINTERS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TERMINAL_ID" INTEGER, "PRINTER_NAME" VARCHAR(60), "VIRTUAL_PRINTER_ID" INTEGER);

CREATE TABLE "APP"."TICKET_TABLE_NUM" ("TICKET_ID" INTEGER NOT NULL, "TABLE_ID" INTEGER);

CREATE TABLE "APP"."MULTIPLIER" ("NAME" VARCHAR(20) NOT NULL, "TICKET_PREFIX" VARCHAR(20), "RATE" DOUBLE, "SORT_ORDER" INTEGER, "DEFAULT_MULTIPLIER" SMALLINT, "MAIN" SMALLINT, "BTN_COLOR" INTEGER, "TEXT_COLOR" INTEGER);

CREATE TABLE "APP"."CUSTOMER_PROPERTIES" ("ID" INTEGER NOT NULL, "PROPERTY_VALUE" VARCHAR(255), "PROPERTY_NAME" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."TAX" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(20) NOT NULL, "RATE" DOUBLE);

CREATE TABLE "APP"."TICKET_ITEM_COOKING_INSTRUCTION" ("TICKET_ITEM_ID" INTEGER NOT NULL, "DESCRIPTION" VARCHAR(60), "PRINTEDTOKITCHEN" SMALLINT, "ITEM_ORDER" INTEGER NOT NULL);

CREATE TABLE "APP"."PRINTER_CONFIGURATION" ("ID" INTEGER NOT NULL, "RECEIPT_PRINTER" VARCHAR(255), "KITCHEN_PRINTER" VARCHAR(255), "PRWTS" SMALLINT, "PRWTP" SMALLINT, "PKWTS" SMALLINT, "PKWTP" SMALLINT, "UNPFT" SMALLINT, "UNPFK" SMALLINT);

CREATE TABLE "APP"."PIZZA_MODIFIER_PRICE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ITEM_SIZE" INTEGER);

CREATE TABLE "APP"."TERMINAL" ("ID" INTEGER NOT NULL, "NAME" VARCHAR(60), "TERMINAL_KEY" VARCHAR(120), "OPENING_BALANCE" DOUBLE, "CURRENT_BALANCE" DOUBLE, "HAS_CASH_DRAWER" SMALLINT, "IN_USE" SMALLINT, "ACTIVE" SMALLINT, "LOCATION" VARCHAR(320), "FLOOR_ID" INTEGER, "ASSIGNED_USER" INTEGER);

CREATE TABLE "APP"."ATTENDENCE_HISTORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CLOCK_IN_TIME" TIMESTAMP, "CLOCK_OUT_TIME" TIMESTAMP, "CLOCK_IN_HOUR" SMALLINT, "CLOCK_OUT_HOUR" SMALLINT, "CLOCKED_OUT" SMALLINT, "USER_ID" INTEGER, "SHIFT_ID" INTEGER, "TERMINAL_ID" INTEGER);

CREATE TABLE "APP"."MENU_MODIFIER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(120), "TRANSLATED_NAME" VARCHAR(120), "PRICE" DOUBLE, "EXTRA_PRICE" DOUBLE, "SORT_ORDER" INTEGER, "BTN_COLOR" INTEGER, "TEXT_COLOR" INTEGER, "ENABLE" SMALLINT, "FIXED_PRICE" SMALLINT, "PRINT_TO_KITCHEN" SMALLINT, "SECTION_WISE_PRICING" SMALLINT, "PIZZA_MODIFIER" SMALLINT, "GROUP_ID" INTEGER, "TAX_ID" INTEGER);

CREATE TABLE "APP"."INVENTORY_VENDOR" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "VISIBLE" SMALLINT, "ADDRESS" VARCHAR(120) NOT NULL, "CITY" VARCHAR(60) NOT NULL, "STATE" VARCHAR(60) NOT NULL, "ZIP" VARCHAR(60) NOT NULL, "COUNTRY" VARCHAR(60) NOT NULL, "EMAIL" VARCHAR(60) NOT NULL, "PHONE" VARCHAR(60) NOT NULL, "FAX" VARCHAR(60));

CREATE TABLE "APP"."DELIVERY_INSTRUCTION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOTES" VARCHAR(220), "CUSTOMER_NO" INTEGER);

CREATE TABLE "APP"."MENUITEM_MODIFIERGROUP" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "MIN_QUANTITY" INTEGER, "MAX_QUANTITY" INTEGER, "SORT_ORDER" INTEGER, "MODIFIER_GROUP" INTEGER, "MENUITEM_MODIFIERGROUP_ID" INTEGER);

CREATE TABLE "APP"."PRINTER_GROUP_PRINTERS" ("PRINTER_ID" INTEGER NOT NULL, "PRINTER_NAME" VARCHAR(255));

CREATE TABLE "APP"."SHOP_FLOOR_TEMPLATE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60), "DEFAULT_FLOOR" SMALLINT, "MAIN" SMALLINT, "FLOOR_ID" INTEGER);

CREATE TABLE "APP"."DATA_UPDATE_INFO" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "LAST_UPDATE_TIME" TIMESTAMP);

CREATE TABLE "APP"."KIT_TICKET_TABLE_NUM" ("KIT_TICKET_ID" INTEGER NOT NULL, "TABLE_ID" INTEGER);

CREATE TABLE "APP"."DRAWER_ASSIGNED_HISTORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TIME" TIMESTAMP, "OPERATION" VARCHAR(60), "A_USER" INTEGER);

CREATE TABLE "APP"."DRAWER_PULL_REPORT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "REPORT_TIME" TIMESTAMP, "REG" VARCHAR(15), "TICKET_COUNT" INTEGER, "BEGIN_CASH" DOUBLE, "NET_SALES" DOUBLE, "SALES_TAX" DOUBLE, "CASH_TAX" DOUBLE, "TOTAL_REVENUE" DOUBLE, "GROSS_RECEIPTS" DOUBLE, "GIFTCERTRETURNCOUNT" INTEGER, "GIFTCERTRETURNAMOUNT" DOUBLE, "GIFTCERTCHANGEAMOUNT" DOUBLE, "CASH_RECEIPT_NO" INTEGER, "CASH_RECEIPT_AMOUNT" DOUBLE, "CREDIT_CARD_RECEIPT_NO" INTEGER, "CREDIT_CARD_RECEIPT_AMOUNT" DOUBLE, "DEBIT_CARD_RECEIPT_NO" INTEGER, "DEBIT_CARD_RECEIPT_AMOUNT" DOUBLE, "REFUND_RECEIPT_COUNT" INTEGER, "REFUND_AMOUNT" DOUBLE, "RECEIPT_DIFFERENTIAL" DOUBLE, "CASH_BACK" DOUBLE, "CASH_TIPS" DOUBLE, "CHARGED_TIPS" DOUBLE, "TIPS_PAID" DOUBLE, "TIPS_DIFFERENTIAL" DOUBLE, "PAY_OUT_NO" INTEGER, "PAY_OUT_AMOUNT" DOUBLE, "DRAWER_BLEED_NO" INTEGER, "DRAWER_BLEED_AMOUNT" DOUBLE, "DRAWER_ACCOUNTABLE" DOUBLE, "CASH_TO_DEPOSIT" DOUBLE, "VARIANCE" DOUBLE, "DELIVERY_CHARGE" DOUBLE, "TOTALVOIDWST" DOUBLE, "TOTALVOID" DOUBLE, "TOTALDISCOUNTCOUNT" INTEGER, "TOTALDISCOUNTAMOUNT" DOUBLE, "TOTALDISCOUNTSALES" DOUBLE, "TOTALDISCOUNTGUEST" INTEGER, "TOTALDISCOUNTPARTYSIZE" INTEGER, "TOTALDISCOUNTCHECKSIZE" INTEGER, "TOTALDISCOUNTPERCENTAGE" DOUBLE, "TOTALDISCOUNTRATIO" DOUBLE, "USER_ID" INTEGER, "TERMINAL_ID" INTEGER);

CREATE TABLE "APP"."TABLE_BOOKING_MAPPING" ("BOOKING_ID" INTEGER NOT NULL, "TABLE_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."MODIFIER_MULTIPLIER_PRICE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "PRICE" DOUBLE, "MULTIPLIER_ID" VARCHAR(20), "MENUMODIFIER_ID" INTEGER, "PIZZA_MODIFIER_PRICE_ID" INTEGER);

CREATE TABLE "APP"."MENU_MODIFIER_GROUP" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60), "TRANSLATED_NAME" VARCHAR(60), "ENABLED" SMALLINT, "EXCLUSIVED" SMALLINT, "REQUIRED" SMALLINT);

CREATE TABLE "APP"."TICKET_ITEM" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ITEM_ID" INTEGER, "ITEM_COUNT" INTEGER, "ITEM_QUANTITY" DOUBLE, "ITEM_NAME" VARCHAR(120), "ITEM_UNIT_NAME" VARCHAR(20), "GROUP_NAME" VARCHAR(120), "CATEGORY_NAME" VARCHAR(120), "ITEM_PRICE" DOUBLE, "ITEM_TAX_RATE" DOUBLE, "SUB_TOTAL" DOUBLE, "SUB_TOTAL_WITHOUT_MODIFIERS" DOUBLE, "DISCOUNT" DOUBLE, "TAX_AMOUNT" DOUBLE, "TAX_AMOUNT_WITHOUT_MODIFIERS" DOUBLE, "TOTAL_PRICE" DOUBLE, "TOTAL_PRICE_WITHOUT_MODIFIERS" DOUBLE, "BEVERAGE" SMALLINT, "INVENTORY_HANDLED" SMALLINT, "PRINT_TO_KITCHEN" SMALLINT, "TREAT_AS_SEAT" SMALLINT, "SEAT_NUMBER" INTEGER, "FRACTIONAL_UNIT" SMALLINT, "HAS_MODIIERS" SMALLINT, "PRINTED_TO_KITCHEN" SMALLINT, "STATUS" VARCHAR(255), "STOCK_AMOUNT_ADJUSTED" SMALLINT, "PIZZA_TYPE" SMALLINT, "TICKET_ID" INTEGER, "PG_ID" INTEGER, "SIZE_MODIFIER_ID" INTEGER, "PIZZA_SECTION_MODE" INTEGER);

CREATE TABLE "APP"."PURCHASE_ORDER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ORDER_ID" VARCHAR(30), "NAME" VARCHAR(30));

CREATE TABLE "APP"."USER_USER_PERMISSION" ("PERMISSIONID" INTEGER NOT NULL, "ELT" VARCHAR(40) NOT NULL);

CREATE TABLE "APP"."EMPLOYEE_IN_OUT_HISTORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "OUT_TIME" TIMESTAMP, "IN_TIME" TIMESTAMP, "OUT_HOUR" SMALLINT, "IN_HOUR" SMALLINT, "CLOCK_OUT" SMALLINT, "USER_ID" INTEGER, "SHIFT_ID" INTEGER, "TERMINAL_ID" INTEGER);

CREATE TABLE "APP"."MENUITEM_PIZZAPIRCE" ("MENU_ITEM_ID" INTEGER NOT NULL, "PIZZA_PRICE_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."TICKET_PROPERTIES" ("ID" INTEGER NOT NULL, "PROPERTY_VALUE" VARCHAR(1000), "PROPERTY_NAME" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."CUSTOM_PAYMENT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60), "REQUIRED_REF_NUMBER" SMALLINT, "REF_NUMBER_FIELD_NAME" VARCHAR(60));

CREATE TABLE "APP"."INVENTORY_TRANSACTION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TRANSACTION_DATE" TIMESTAMP, "QUANTITY" INTEGER, "UNIT_PRICE" DOUBLE, "REMARK" VARCHAR(255), "TRAN_TYPE" INTEGER, "REFERENCE_ID" INTEGER, "ITEM_ID" INTEGER, "VENDOR_ID" INTEGER, "FROM_WAREHOUSE_ID" INTEGER, "TO_WAREHOUSE_ID" INTEGER);

CREATE TABLE "APP"."ORDER_TYPE_PROPERTIES" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "OTYPE" VARCHAR(16), "ALIAS" VARCHAR(40), "BTN_COLOR" INTEGER, "TEXT_COLOR" INTEGER, "VISIBLE" SMALLINT, "POST_PAID" SMALLINT);

CREATE TABLE "APP"."TICKET" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CREATE_DATE" TIMESTAMP, "CLOSING_DATE" TIMESTAMP, "ACTIVE_DATE" TIMESTAMP, "DELIVEERY_DATE" TIMESTAMP, "CREATION_HOUR" INTEGER, "PAID" SMALLINT, "VOIDED" SMALLINT, "VOID_REASON" VARCHAR(255), "WASTED" SMALLINT, "REFUNDED" SMALLINT, "SETTLED" SMALLINT, "DRAWER_RESETTED" SMALLINT, "SUB_TOTAL" DOUBLE, "TOTAL_DISCOUNT" DOUBLE, "TOTAL_TAX" DOUBLE, "TOTAL_PRICE" DOUBLE, "PAID_AMOUNT" DOUBLE, "DUE_AMOUNT" DOUBLE, "ADVANCE_AMOUNT" DOUBLE, "NUMBER_OF_GUESTS" INTEGER, "STATUS" VARCHAR(30), "IS_TAX_EXEMPT" SMALLINT, "IS_RE_OPENED" SMALLINT, "SERVICE_CHARGE" DOUBLE, "DELIVERY_CHARGE" DOUBLE, "DELIVERY_ADDRESS" VARCHAR(120), "CUSTOMER_PICKEUP" SMALLINT, "DELIVERY_EXTRA_INFO" VARCHAR(255), "TICKET_TYPE" VARCHAR(20), "SHIFT_ID" INTEGER, "OWNER_ID" INTEGER, "DRIVER_ID" INTEGER, "GRATUITY_ID" INTEGER, "VOID_BY_USER" INTEGER, "TERMINAL_ID" INTEGER, "CUSTOMER_ID" INTEGER, "BAR_TAB" SMALLINT, "GLOBAL_ID" VARCHAR(16));

CREATE TABLE "APP"."DRAWER_PULL_REPORT_VOIDTICKETS" ("DPREPORT_ID" INTEGER NOT NULL, "CODE" INTEGER, "REASON" VARCHAR(255), "HAST" VARCHAR(255), "QUANTITY" INTEGER, "AMOUNT" DOUBLE);

CREATE TABLE "APP"."PACKAGING_UNIT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(30), "SHORT_NAME" VARCHAR(10), "FACTOR" DOUBLE, "BASEUNIT" SMALLINT, "DIMENSION" VARCHAR(30));

CREATE TABLE "APP"."ZIP_CODE_VS_DELIVERY_CHARGE" ("AUTO_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ZIP_CODE" VARCHAR(10) NOT NULL, "DELIVERY_CHARGE" DOUBLE NOT NULL);

CREATE TABLE "APP"."PRINTER_GROUP" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "IS_DEFAULT" SMALLINT);

CREATE TABLE "APP"."TICKET_COUPON_DISCOUNT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "COUPON_DISCOUNT_ID" INTEGER, "NAME" VARCHAR(30), "TYPE" INTEGER, "VALUE" DOUBLE, "TICKET_ID" INTEGER, "D_ORDER" INTEGER);

CREATE TABLE "APP"."ORDER_TYPE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(120) NOT NULL, "ENABLED" SMALLINT, "SHOW_TABLE_SELECTION" SMALLINT, "SHOW_GUEST_SELECTION" SMALLINT, "SHOULD_PRINT_TO_KITCHEN" SMALLINT, "PREPAID" SMALLINT, "CLOSE_ON_PAID" SMALLINT, "REQUIRED_CUSTOMER_DATA" SMALLINT, "DELIVERY" SMALLINT, "SHOW_ITEM_BARCODE" SMALLINT, "SHOW_IN_LOGIN_SCREEN" SMALLINT, "CONSOLIDATE_TIEMS_IN_RECEIPT" SMALLINT, "ALLOW_SEAT_BASED_ORDER" SMALLINT, "HIDE_ITEM_WITH_EMPTY_INVENTORY" SMALLINT, "HAS_FORHERE_AND_TOGO" SMALLINT, "PRE_AUTH_CREDIT_CARD" SMALLINT, "BAR_TAB" SMALLINT, "SHOW_PRICE_ON_BUTTON" SMALLINT, "SHOW_STOCK_COUNT_ON_BUTTON" SMALLINT, "SHOW_UNIT_PRICE_IN_TICKET_GRID" SMALLINT);

CREATE TABLE "APP"."DELIVERY_CONFIGURATION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "UNIT_NAME" VARCHAR(20), "UNIT_SYMBOL" VARCHAR(8), "CHARGE_BY_ZIP_CODE" SMALLINT);

CREATE TABLE "APP"."INVENTORY_ITEM" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CREATE_TIME" TIMESTAMP, "LAST_UPDATE_DATE" TIMESTAMP, "NAME" VARCHAR(60), "PACKAGE_BARCODE" VARCHAR(30), "UNIT_BARCODE" VARCHAR(30), "UNIT_PER_PACKAGE" DOUBLE, "SORT_ORDER" INTEGER, "PACKAGE_REORDER_LEVEL" INTEGER, "PACKAGE_REPLENISH_LEVEL" INTEGER, "DESCRIPTION" VARCHAR(255), "AVERAGE_PACKAGE_PRICE" DOUBLE, "TOTAL_PACKAGES" INTEGER, "TOTAL_RECEPIE_UNITS" DOUBLE, "UNIT_PURCHASE_PRICE" DOUBLE, "UNIT_SELLING_PRICE" DOUBLE, "VISIBLE" SMALLINT, "PUNIT_ID" INTEGER, "RECIPE_UNIT_ID" INTEGER, "ITEM_GROUP_ID" INTEGER, "ITEM_LOCATION_ID" INTEGER, "ITEM_VENDOR_ID" INTEGER);

CREATE TABLE "APP"."TRANSACTIONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "PAYMENT_TYPE" VARCHAR(30) NOT NULL, "GLOBAL_ID" VARCHAR(16), "TRANSACTION_TIME" TIMESTAMP, "AMOUNT" DOUBLE, "TIPS_AMOUNT" DOUBLE, "TIPS_EXCEED_AMOUNT" DOUBLE, "TENDER_AMOUNT" DOUBLE, "TRANSACTION_TYPE" VARCHAR(30) NOT NULL, "CUSTOM_PAYMENT_NAME" VARCHAR(60), "CUSTOM_PAYMENT_REF" VARCHAR(120), "CUSTOM_PAYMENT_FIELD_NAME" VARCHAR(60), "PAYMENT_SUB_TYPE" VARCHAR(40) NOT NULL, "CAPTURED" SMALLINT, "VOIDED" SMALLINT, "AUTHORIZABLE" SMALLINT, "CARD_HOLDER_NAME" VARCHAR(60), "CARD_NUMBER" VARCHAR(40), "CARD_AUTH_CODE" VARCHAR(30), "CARD_TYPE" VARCHAR(20), "CARD_TRANSACTION_ID" VARCHAR(255), "CARD_MERCHANT_GATEWAY" VARCHAR(60), "CARD_READER" VARCHAR(30), "CARD_AID" VARCHAR(120), "CARD_ARQC" VARCHAR(120), "CARD_EXT_DATA" VARCHAR(255), "GIFT_CERT_NUMBER" VARCHAR(64), "GIFT_CERT_FACE_VALUE" DOUBLE, "GIFT_CERT_PAID_AMOUNT" DOUBLE, "GIFT_CERT_CASH_BACK_AMOUNT" DOUBLE, "DRAWER_RESETTED" SMALLINT, "NOTE" VARCHAR(255), "TERMINAL_ID" INTEGER, "TICKET_ID" INTEGER, "USER_ID" INTEGER, "PAYOUT_REASON_ID" INTEGER, "PAYOUT_RECEPIENT_ID" INTEGER);

CREATE TABLE "APP"."INVENTORY_META_CODE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TYPE" VARCHAR(255), "CODE_TEXT" VARCHAR(255), "CODE_NO" INTEGER, "DESCRIPTION" VARCHAR(255));

CREATE TABLE "APP"."TICKET_ITEM_ADDON_RELATION" ("TICKET_ITEM_ID" INTEGER NOT NULL, "MODIFIER_ID" INTEGER NOT NULL, "LIST_ORDER" INTEGER NOT NULL);

CREATE TABLE "APP"."TABLE_TYPE_RELATION" ("TABLE_ID" INTEGER NOT NULL, "TYPE_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."TICKET_ITEM_MODIFIER_RELATION" ("TICKET_ITEM_ID" INTEGER NOT NULL, "MODIFIER_ID" INTEGER NOT NULL, "LIST_ORDER" INTEGER NOT NULL);

CREATE TABLE "APP"."MENU_ITEM_SIZE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60), "TRANSLATED_NAME" VARCHAR(60), "DESCRIPTION" VARCHAR(120), "SORT_ORDER" INTEGER, "SIZE_IN_INCH" DOUBLE, "DEFAULT_SIZE" SMALLINT);

CREATE TABLE "APP"."TRANSACTION_PROPERTIES" ("ID" INTEGER NOT NULL, "PROPERTY_VALUE" VARCHAR(255), "PROPERTY_NAME" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."DELIVERY_CHARGE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(220), "ZIP_CODE" VARCHAR(20), "START_RANGE" DOUBLE, "END_RANGE" DOUBLE, "CHARGE_AMOUNT" DOUBLE);

CREATE TABLE "APP"."COUPON_AND_DISCOUNT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(120), "TYPE" INTEGER, "BARCODE" VARCHAR(120), "QUALIFICATION_TYPE" INTEGER, "APPLY_TO_ALL" SMALLINT, "MINIMUM_BUY" INTEGER, "MAXIMUM_OFF" INTEGER, "VALUE" DOUBLE, "EXPIRY_DATE" TIMESTAMP, "ENABLED" SMALLINT, "AUTO_APPLY" SMALLINT, "MODIFIABLE" SMALLINT, "NEVER_EXPIRE" SMALLINT, "UUID" VARCHAR(36));

CREATE TABLE "APP"."MENUGROUP_DISCOUNT" ("DISCOUNT_ID" INTEGER NOT NULL, "MENUGROUP_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."PAYOUT_RECEPIENTS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(255));

CREATE TABLE "APP"."TICKET_ITEM_MODIFIER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ITEM_ID" INTEGER, "GROUP_ID" INTEGER, "ITEM_COUNT" INTEGER, "MODIFIER_NAME" VARCHAR(120), "MODIFIER_PRICE" DOUBLE, "MODIFIER_TAX_RATE" DOUBLE, "MODIFIER_TYPE" INTEGER, "SUBTOTAL_PRICE" DOUBLE, "TOTAL_PRICE" DOUBLE, "TAX_AMOUNT" DOUBLE, "INFO_ONLY" SMALLINT, "SECTION_NAME" VARCHAR(20), "MULTIPLIER_NAME" VARCHAR(20), "PRINT_TO_KITCHEN" SMALLINT, "SECTION_WISE_PRICING" SMALLINT, "STATUS" VARCHAR(10), "PRINTED_TO_KITCHEN" SMALLINT, "TICKET_ITEM_ID" INTEGER);

CREATE TABLE "APP"."VIRTUALPRINTER_ORDER_TYPE" ("PRINTER_ID" INTEGER NOT NULL, "ORDER_TYPE" VARCHAR(255));

CREATE TABLE "APP"."CASH_DRAWER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TERMINAL_ID" INTEGER);

CREATE TABLE "APP"."MENUMODIFIER_PIZZAMODIFIERPRICE" ("MENUMODIFIER_ID" INTEGER NOT NULL, "PIZZAMODIFIERPRICE_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."PAYOUT_REASONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "REASON" VARCHAR(255));

CREATE TABLE "APP"."SHOP_TABLE_TYPE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DESCRIPTION" VARCHAR(120), "NAME" VARCHAR(40));

CREATE TABLE "APP"."SHOP_FLOOR_TEMPLATE_PROPERTIES" ("ID" INTEGER NOT NULL, "PROPERTY_VALUE" VARCHAR(60), "PROPERTY_NAME" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."CURRENCY_BALANCE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "BALANCE" DOUBLE, "CURRENCY_ID" INTEGER, "CASH_DRAWER_ID" INTEGER, "DPR_ID" INTEGER);

CREATE TABLE "APP"."CURRENCY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CODE" VARCHAR(20), "NAME" VARCHAR(30), "SYMBOL" VARCHAR(10), "EXCHANGE_RATE" DOUBLE, "TOLERANCE" DOUBLE, "BUY_PRICE" DOUBLE, "SALES_PRICE" DOUBLE, "MAIN" SMALLINT);

CREATE TABLE "APP"."VIRTUAL_PRINTER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "TYPE" INTEGER, "PRIORITY" INTEGER, "ENABLED" SMALLINT);

CREATE TABLE "APP"."TICKETITEM_MODIFIERGROUP" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "SECTION_NAME" VARCHAR(120), "MIN_QUANTITY" INTEGER, "MAX_QUANTITY" INTEGER, "SHOW_SECTION_NAME" SMALLINT, "MAIN_SECTION" SMALLINT, "SORT_ORDER" INTEGER, "PARENT" INTEGER, "GROUP_ID" INTEGER, "TICKETITEM_ID" INTEGER, "ITEM_ORDER" INTEGER);

CREATE TABLE "APP"."INVENTORY_UNIT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "SHORT_NAME" VARCHAR(255), "LONG_NAME" VARCHAR(255), "ALT_NAME" VARCHAR(255), "CONV_FACTOR1" VARCHAR(255), "CONV_FACTOR2" VARCHAR(255), "CONV_FACTOR3" VARCHAR(255));

CREATE TABLE "APP"."CUSTOMER" ("AUTO_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "LOYALTY_NO" VARCHAR(30), "LOYALTY_POINT" INTEGER, "SOCIAL_SECURITY_NUMBER" VARCHAR(60), "PICTURE" VARCHAR (20480) FOR BIT DATA, "HOMEPHONE_NO" VARCHAR(30), "MOBILE_NO" VARCHAR(30), "WORKPHONE_NO" VARCHAR(30), "EMAIL" VARCHAR(40), "SALUTATION" VARCHAR(60), "FIRST_NAME" VARCHAR(60), "LAST_NAME" VARCHAR(60), "NAME" VARCHAR(120), "DOB" VARCHAR(16), "SSN" VARCHAR(30), "ADDRESS" VARCHAR(220), "CITY" VARCHAR(30), "STATE" VARCHAR(30), "ZIP_CODE" VARCHAR(10), "COUNTRY" VARCHAR(30), "VIP" SMALLINT, "CREDIT_LIMIT" DOUBLE, "CREDIT_SPENT" DOUBLE, "CREDIT_CARD_NO" VARCHAR(30), "NOTE" VARCHAR(255));

CREATE TABLE "APP"."INVENTORY_WAREHOUSE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "VISIBLE" SMALLINT);

CREATE TABLE "APP"."TICKET_ITEM_DISCOUNT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DISCOUNT_ID" INTEGER, "NAME" VARCHAR(30), "TYPE" INTEGER, "AUTO_APPLY" SMALLINT, "MINIMUM_QUANTITY" INTEGER, "VALUE" DOUBLE, "AMOUNT" DOUBLE, "TICKET_ITEMID" INTEGER);

CREATE TABLE "APP"."KITCHEN_TICKET_ITEM" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "COOKABLE" SMALLINT, "TICKET_ITEM_ID" INTEGER, "TICKET_ITEM_MODIFIER_ID" INTEGER, "MENU_ITEM_CODE" VARCHAR(255), "MENU_ITEM_NAME" VARCHAR(120), "MENU_ITEM_GROUP_ID" INTEGER, "MENU_ITEM_GROUP_NAME" VARCHAR(120), "QUANTITY" INTEGER, "FRACTIONAL_QUANTITY" DOUBLE, "FRACTIONAL_UNIT" SMALLINT, "UNIT_NAME" VARCHAR(20), "SORT_ORDER" INTEGER, "VOIDED" SMALLINT, "STATUS" VARCHAR(30), "KITHEN_TICKET_ID" INTEGER, "ITEM_ORDER" INTEGER);

CREATE TABLE "APP"."CASH_DRAWER_RESET_HISTORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "RESET_TIME" TIMESTAMP, "USER_ID" INTEGER);

CREATE TABLE "APP"."USER_PERMISSION" ("NAME" VARCHAR(40) NOT NULL);

CREATE TABLE "APP"."USER_TYPE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "P_NAME" VARCHAR(60));

CREATE TABLE "APP"."ITEM_ORDER_TYPE" ("MENU_ITEM_ID" INTEGER NOT NULL, "ORDER_TYPE_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."RESTAURANT" ("ID" INTEGER NOT NULL, "UNIQUE_ID" INTEGER, "NAME" VARCHAR(120), "ADDRESS_LINE1" VARCHAR(60), "ADDRESS_LINE2" VARCHAR(60), "ADDRESS_LINE3" VARCHAR(60), "ZIP_CODE" VARCHAR(10), "TELEPHONE" VARCHAR(16), "CAPACITY" INTEGER, "TABLES" INTEGER, "CNAME" VARCHAR(20), "CSYMBOL" VARCHAR(10), "SC_PERCENTAGE" DOUBLE, "GRATUITY_PERCENTAGE" DOUBLE, "TICKET_FOOTER" VARCHAR(60), "PRICE_INCLUDES_TAX" SMALLINT, "ALLOW_MODIFIER_MAX_EXCEED" SMALLINT);

CREATE TABLE "APP"."RECEPIE_ITEM" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "PERCENTAGE" DOUBLE, "INVENTORY_DEDUCTABLE" SMALLINT, "INVENTORY_ITEM" INTEGER, "RECEPIE_ID" INTEGER);

CREATE TABLE "APP"."GLOBAL_CONFIG" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "POS_KEY" VARCHAR(60), "POS_VALUE" VARCHAR(220));

CREATE TABLE "APP"."RECEPIE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "MENU_ITEM" INTEGER);

CREATE TABLE "APP"."COOKING_INSTRUCTION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DESCRIPTION" VARCHAR(60));

CREATE TABLE "APP"."TABLE_BOOKING_INFO" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "FROM_DATE" TIMESTAMP, "TO_DATE" TIMESTAMP, "GUEST_COUNT" INTEGER, "STATUS" VARCHAR(30), "PAYMENT_STATUS" VARCHAR(30), "BOOKING_CONFIRM" VARCHAR(30), "BOOKING_CHARGE" DOUBLE, "REMAINING_BALANCE" DOUBLE, "PAID_AMOUNT" DOUBLE, "BOOKING_ID" VARCHAR(30), "BOOKING_TYPE" VARCHAR(30), "USER_ID" INTEGER, "CUSTOMER_ID" INTEGER);

CREATE TABLE "APP"."TICKET_DISCOUNT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DISCOUNT_ID" INTEGER, "NAME" VARCHAR(30), "TYPE" INTEGER, "AUTO_APPLY" SMALLINT, "MINIMUM_AMOUNT" INTEGER, "VALUE" DOUBLE, "TICKET_ID" INTEGER);

CREATE TABLE "APP"."PIZZA_CRUST" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60), "TRANSLATED_NAME" VARCHAR(60), "DESCRIPTION" VARCHAR(120), "SORT_ORDER" INTEGER, "DEFAULT_CRUST" SMALLINT);

CREATE TABLE "APP"."DELIVERY_ADDRESS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ADDRESS" VARCHAR(320), "PHONE_EXTENSION" VARCHAR(10), "ROOM_NO" VARCHAR(30), "DISTANCE" DOUBLE, "CUSTOMER_ID" INTEGER);

CREATE TABLE "APP"."MENUCATEGORY_DISCOUNT" ("DISCOUNT_ID" INTEGER NOT NULL, "MENUCATEGORY_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."MENUITEM_DISCOUNT" ("DISCOUNT_ID" INTEGER NOT NULL, "MENUITEM_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."MENU_ITEM_TERMINAL_REF" ("MENU_ITEM_ID" INTEGER NOT NULL, "TERMINAL_ID" INTEGER NOT NULL);

CREATE TABLE "APP"."MENUITEM_SHIFT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "SHIFT_PRICE" DOUBLE, "SHIFT_ID" INTEGER, "MENUITEM_ID" INTEGER);

CREATE TABLE "APP"."MENU_GROUP" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(120) NOT NULL, "TRANSLATED_NAME" VARCHAR(120), "VISIBLE" SMALLINT, "SORT_ORDER" INTEGER, "BTN_COLOR" INTEGER, "TEXT_COLOR" INTEGER, "CATEGORY_ID" INTEGER);

CREATE TABLE "APP"."INVENTORY_GROUP" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "VISIBLE" SMALLINT);

CREATE TABLE "APP"."MENU_ITEM" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(120) NOT NULL, "DESCRIPTION" VARCHAR(255), "UNIT_NAME" VARCHAR(20), "TRANSLATED_NAME" VARCHAR(120), "BARCODE" VARCHAR(120), "BUY_PRICE" DOUBLE NOT NULL, "STOCK_AMOUNT" DOUBLE, "PRICE" DOUBLE NOT NULL, "DISCOUNT_RATE" DOUBLE, "VISIBLE" SMALLINT, "DISABLE_WHEN_STOCK_AMOUNT_IS_ZERO" SMALLINT, "SORT_ORDER" INTEGER, "BTN_COLOR" INTEGER, "TEXT_COLOR" INTEGER, "IMAGE" VARCHAR (20480) FOR BIT DATA, "SHOW_IMAGE_ONLY" SMALLINT, "FRACTIONAL_UNIT" SMALLINT, "PIZZA_TYPE" SMALLINT, "DEFAULT_SELL_PORTION" INTEGER, "GROUP_ID" INTEGER, "TAX_ID" INTEGER, "RECEPIE" INTEGER, "PG_ID" INTEGER);

CREATE TABLE "APP"."GRATUITY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "AMOUNT" DOUBLE, "PAID" SMALLINT, "REFUNDED" SMALLINT, "TICKET_ID" INTEGER, "OWNER_ID" INTEGER, "TERMINAL_ID" INTEGER);

CREATE TABLE "APP"."ACTION_HISTORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ACTION_TIME" TIMESTAMP, "ACTION_NAME" VARCHAR(255), "DESCRIPTION" VARCHAR(255), "USER_ID" INTEGER);

CREATE TABLE "APP"."INVENTORY_LOCATION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "SORT_ORDER" INTEGER, "VISIBLE" SMALLINT, "WAREHOUSE_ID" INTEGER);

CREATE TABLE "APP"."VOID_REASONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "REASON_TEXT" VARCHAR(255));

CREATE TABLE "APP"."MENU_MODIFIER_PROPERTIES" ("MENU_MODIFIER_ID" INTEGER NOT NULL, "PROPERTY_VALUE" VARCHAR(100), "PROPERTY_NAME" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."MENU_CATEGORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(120) NOT NULL, "TRANSLATED_NAME" VARCHAR(120), "VISIBLE" SMALLINT, "BEVERAGE" SMALLINT, "SORT_ORDER" INTEGER, "BTN_COLOR" INTEGER, "TEXT_COLOR" INTEGER);

CREATE TABLE "APP"."PIZZA_PRICE" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "PRICE" DOUBLE, "MENU_ITEM_SIZE" INTEGER, "CRUST" INTEGER, "ORDER_TYPE" INTEGER);

CREATE TABLE "APP"."SHIFT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(60) NOT NULL, "START_TIME" TIMESTAMP, "END_TIME" TIMESTAMP, "SHIFT_LEN" BIGINT);

CREATE TABLE "APP"."KITCHEN_TICKET" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TICKET_ID" INTEGER, "CREATE_DATE" TIMESTAMP, "CLOSE_DATE" TIMESTAMP, "VOIDED" SMALLINT, "SEQUENCE_NUMBER" INTEGER, "STATUS" VARCHAR(30), "SERVER_NAME" VARCHAR(30), "TICKET_TYPE" VARCHAR(20), "PG_ID" INTEGER);

-- ----------------------------------------------
-- DDL Statements for indexes
-- ----------------------------------------------

CREATE INDEX "APP"."MG_ENABLE" ON "APP"."MENU_MODIFIER_GROUP" ("ENABLED");

CREATE INDEX "APP"."MODIFIERENABLED" ON "APP"."MENU_MODIFIER" ("ENABLE");

CREATE INDEX "APP"."DRAWERRESETTED" ON "APP"."TICKET" ("DRAWER_RESETTED");

CREATE INDEX "APP"."TICKETCREATEDATE" ON "APP"."TICKET" ("CREATE_DATE");

CREATE INDEX "APP"."TICKETACTIVEDATE" ON "APP"."TICKET" ("ACTIVE_DATE");

CREATE INDEX "APP"."TICKETSETTLED" ON "APP"."TICKET" ("SETTLED");

CREATE INDEX "APP"."DELIVERYDATE" ON "APP"."TICKET" ("DELIVEERY_DATE");

CREATE INDEX "APP"."CREATIONHOUR" ON "APP"."TICKET" ("CREATION_HOUR");

CREATE INDEX "APP"."TICKETPAID" ON "APP"."TICKET" ("PAID");

CREATE INDEX "APP"."TICKETCLOSINGDATE" ON "APP"."TICKET" ("CLOSING_DATE");

CREATE INDEX "APP"."TICKETVOIDED" ON "APP"."TICKET" ("VOIDED");

CREATE INDEX "APP"."FROMDATE" ON "APP"."TABLE_BOOKING_INFO" ("FROM_DATE");

CREATE INDEX "APP"."TODATE" ON "APP"."TABLE_BOOKING_INFO" ("TO_DATE");

CREATE INDEX "APP"."FOOD_CATEGORY_VISIBLE" ON "APP"."MENU_CATEGORY" ("VISIBLE");

CREATE INDEX "APP"."TRAN_DRAWER_RESETTED" ON "APP"."TRANSACTIONS" ("DRAWER_RESETTED");

CREATE INDEX "APP"."DRAWER_REPORT_TIME" ON "APP"."DRAWER_PULL_REPORT" ("REPORT_TIME");

CREATE INDEX "APP"."MENUGROUPVISIBLE" ON "APP"."MENU_GROUP" ("VISIBLE");

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE "APP"."PIZZA_CRUST" ADD CONSTRAINT "SQL250911091208260" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET_COUPON_DISCOUNT" ADD CONSTRAINT "SQL150804020927290" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_UNIT" ADD CONSTRAINT "SQL250911091208001" PRIMARY KEY ("ID");

ALTER TABLE "APP"."KITCHEN_TICKET" ADD CONSTRAINT "SQL250911091208040" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DELIVERY_ADDRESS" ADD CONSTRAINT "SQL250911091207870" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_ITEM_PROPERTIES" ADD CONSTRAINT "SQL250911091208140" PRIMARY KEY ("MENU_ITEM_ID", "PROPERTY_NAME");

ALTER TABLE "APP"."TICKET_ITEM_DISCOUNT" ADD CONSTRAINT "SQL250911091208571" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_MODIFIER_GROUP" ADD CONSTRAINT "SQL250911091208170" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TERMINAL_PRINTERS" ADD CONSTRAINT "SQL250911091208510" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET_ITEM" ADD CONSTRAINT "SQL161230161833790" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ATTENDENCE_HISTORY" ADD CONSTRAINT "SQL250911091207740" PRIMARY KEY ("ID");

ALTER TABLE "APP"."GRATUITY" ADD CONSTRAINT "SQL250911091207950" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PAYOUT_RECEPIENTS" ADD CONSTRAINT "SQL250911091208250" PRIMARY KEY ("ID");

ALTER TABLE "APP"."CURRENCY" ADD CONSTRAINT "SQL250911091207791" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_TRANSACTION" ADD CONSTRAINT "SQL250911091208000" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DATA_UPDATE_INFO" ADD CONSTRAINT "SQL250911091207860" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_ITEM" ADD CONSTRAINT "SQL250911091208130" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET_ITEM_COOKING_INSTRUCTION" ADD CONSTRAINT "SQL250911091208570" PRIMARY KEY ("TICKET_ITEM_ID", "ITEM_ORDER");

ALTER TABLE "APP"."MENU_MODIFIER" ADD CONSTRAINT "SQL250911091208160" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ACTION_HISTORY" ADD CONSTRAINT "SQL250911091207730" PRIMARY KEY ("ID");

ALTER TABLE "APP"."SHOP_FLOOR" ADD CONSTRAINT "SQL250911091208410" PRIMARY KEY ("ID");

ALTER TABLE "APP"."RESTAURANT" ADD CONSTRAINT "SQL250911091208380" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "SQL150804020926840" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PACKAGING_UNIT" ADD CONSTRAINT "SQL250911091208230" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TABLE_BOOKING_INFO" ADD CONSTRAINT "SQL250911091208470" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_LOCATION" ADD CONSTRAINT "SQL250911091207970" PRIMARY KEY ("ID");

ALTER TABLE "APP"."RECEPIE_ITEM" ADD CONSTRAINT "SQL250911091208370" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USER_TYPE" ADD CONSTRAINT "SQL250911091208651" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_CATEGORY" ADD CONSTRAINT "SQL250911091208101" PRIMARY KEY ("ID");

ALTER TABLE "APP"."CUSTOMER_PROPERTIES" ADD CONSTRAINT "SQL250911091207820" PRIMARY KEY ("ID", "PROPERTY_NAME");

ALTER TABLE "APP"."PIZZA_PRICE" ADD CONSTRAINT "SQL250911091208290" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_WAREHOUSE" ADD CONSTRAINT "SQL250911091208030" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DELIVERY_CONFIGURATION" ADD CONSTRAINT "SQL250911091207880" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ORDER_TYPE_PROPERTIES" ADD CONSTRAINT "SQL150804020921900" PRIMARY KEY ("ID");

ALTER TABLE "APP"."RECEPIE" ADD CONSTRAINT "SQL250911091208350" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET_ITEM_MODIFIER_RELATION" ADD CONSTRAINT "SQL250911091208591" PRIMARY KEY ("TICKET_ITEM_ID", "LIST_ORDER");

ALTER TABLE "APP"."TICKET_DISCOUNT" ADD CONSTRAINT "SQL250911091208540" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_ITEM" ADD CONSTRAINT "SQL250911091207961" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USER_PERMISSION" ADD CONSTRAINT "SQL250911091208650" PRIMARY KEY ("NAME");

ALTER TABLE "APP"."ZIP_CODE_VS_DELIVERY_CHARGE" ADD CONSTRAINT "SQL250911091208711" PRIMARY KEY ("AUTO_ID");

ALTER TABLE "APP"."CUSTOMER" ADD CONSTRAINT "SQL250911091207811" PRIMARY KEY ("AUTO_ID");

ALTER TABLE "APP"."SHIFT" ADD CONSTRAINT "SQL250911091208390" UNIQUE ("NAME");

ALTER TABLE "APP"."SHIFT" ADD CONSTRAINT "SQL250911091208391" PRIMARY KEY ("ID");

ALTER TABLE "APP"."SHOP_TABLE" ADD CONSTRAINT "SQL250911091208450" PRIMARY KEY ("ID");

ALTER TABLE "APP"."KITCHEN_TICKET_ITEM" ADD CONSTRAINT "SQL250911091208050" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_MODIFIER_PROPERTIES" ADD CONSTRAINT "SQL250911091208180" PRIMARY KEY ("MENU_MODIFIER_ID", "PROPERTY_NAME");

ALTER TABLE "APP"."CASH_DRAWER" ADD CONSTRAINT "SQL250911091207760" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_GROUP" ADD CONSTRAINT "SQL250911091207960" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "SQL250911091208640" UNIQUE ("USER_PASS");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "SQL250911091208641" PRIMARY KEY ("AUTO_ID");

ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "SQL250911091208620" PRIMARY KEY ("ID");

ALTER TABLE "APP"."CURRENCY_BALANCE" ADD CONSTRAINT "SQL250911091207810" PRIMARY KEY ("ID");

ALTER TABLE "APP"."SHOP_FLOOR_TEMPLATE_PROPERTIES" ADD CONSTRAINT "SQL250911091208440" PRIMARY KEY ("ID", "PROPERTY_NAME");

ALTER TABLE "APP"."DRAWER_PULL_REPORT" ADD CONSTRAINT "SQL250911091207920" PRIMARY KEY ("ID");

ALTER TABLE "APP"."SHOP_FLOOR_TEMPLATE" ADD CONSTRAINT "SQL250911091208420" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENUITEM_SHIFT" ADD CONSTRAINT "SQL250911091208100" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TERMINAL" ADD CONSTRAINT "SQL250911091208501" PRIMARY KEY ("ID");

ALTER TABLE "APP"."VIRTUAL_PRINTER" ADD CONSTRAINT "SQL250911091208690" UNIQUE ("NAME");

ALTER TABLE "APP"."VIRTUAL_PRINTER" ADD CONSTRAINT "SQL250911091208691" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENUITEM_MODIFIERGROUP" ADD CONSTRAINT "SQL161230161828140" PRIMARY KEY ("ID");

ALTER TABLE "APP"."GLOBAL_CONFIG" ADD CONSTRAINT "SQL250911091207940" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PAYOUT_REASONS" ADD CONSTRAINT "SQL250911091208240" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DRAWER_ASSIGNED_HISTORY" ADD CONSTRAINT "SQL250911091207900" PRIMARY KEY ("ID");

ALTER TABLE "APP"."COUPON_AND_DISCOUNT" ADD CONSTRAINT "SQL250911091207790" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_META_CODE" ADD CONSTRAINT "SQL250911091207990" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET_ITEM_ADDON_RELATION" ADD CONSTRAINT "SQL250911091208560" PRIMARY KEY ("TICKET_ITEM_ID", "LIST_ORDER");

ALTER TABLE "APP"."MENU_GROUP" ADD CONSTRAINT "SQL250911091208110" PRIMARY KEY ("ID");

ALTER TABLE "APP"."CUSTOM_PAYMENT" ADD CONSTRAINT "SQL250911091207830" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TAX" ADD CONSTRAINT "SQL250911091208500" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USER_USER_PERMISSION" ADD CONSTRAINT "SQL250911091208670" PRIMARY KEY ("PERMISSIONID", "ELT");

ALTER TABLE "APP"."PRINTER_CONFIGURATION" ADD CONSTRAINT "SQL250911091208300" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKETITEM_MODIFIERGROUP" ADD CONSTRAINT "SQL161230161833470" PRIMARY KEY ("ID");

ALTER TABLE "APP"."EMPLOYEE_IN_OUT_HISTORY" ADD CONSTRAINT "SQL250911091207930" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DELIVERY_INSTRUCTION" ADD CONSTRAINT "SQL250911091207890" PRIMARY KEY ("ID");

ALTER TABLE "APP"."COOKING_INSTRUCTION" ADD CONSTRAINT "SQL250911091207780" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MULTIPLIER" ADD CONSTRAINT "SQL250911091208200" PRIMARY KEY ("NAME");

ALTER TABLE "APP"."TICKET_PROPERTIES" ADD CONSTRAINT "SQL250911091208610" PRIMARY KEY ("ID", "PROPERTY_NAME");

ALTER TABLE "APP"."PRINTER_GROUP" ADD CONSTRAINT "SQL250911091208310" UNIQUE ("NAME");

ALTER TABLE "APP"."PRINTER_GROUP" ADD CONSTRAINT "SQL250911091208311" PRIMARY KEY ("ID");

ALTER TABLE "APP"."SHOP_TABLE_TYPE" ADD CONSTRAINT "SQL250911091208460" PRIMARY KEY ("ID");

ALTER TABLE "APP"."CASH_DRAWER_RESET_HISTORY" ADD CONSTRAINT "SQL250911091207761" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MODIFIER_MULTIPLIER_PRICE" ADD CONSTRAINT "SQL250911091208181" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PIZZA_MODIFIER_PRICE" ADD CONSTRAINT "SQL250911091208280" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TRANSACTION_PROPERTIES" ADD CONSTRAINT "SQL250911091208630" PRIMARY KEY ("ID", "PROPERTY_NAME");

ALTER TABLE "APP"."ORDER_TYPE" ADD CONSTRAINT "SQL250911091208210" UNIQUE ("NAME");

ALTER TABLE "APP"."ORDER_TYPE" ADD CONSTRAINT "SQL250911091208211" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVENTORY_VENDOR" ADD CONSTRAINT "SQL250911091208020" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DELIVERY_CHARGE" ADD CONSTRAINT "SQL250911091207871" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_ITEM_SIZE" ADD CONSTRAINT "SQL250911091208141" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TICKET_ITEM_MODIFIER" ADD CONSTRAINT "SQL250911091208590" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PURCHASE_ORDER" ADD CONSTRAINT "SQL250911091208340" PRIMARY KEY ("ID");

ALTER TABLE "APP"."VOID_REASONS" ADD CONSTRAINT "SQL250911091208710" PRIMARY KEY ("ID");

-- foreign
ALTER TABLE "APP"."MENUCATEGORY_DISCOUNT" ADD CONSTRAINT "FK4F8523E38D9EA931" FOREIGN KEY ("MENUCATEGORY_ID") REFERENCES "APP"."MENU_CATEGORY" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUCATEGORY_DISCOUNT" ADD CONSTRAINT "FK4F8523E3D3E91E11" FOREIGN KEY ("DISCOUNT_ID") REFERENCES "APP"."COUPON_AND_DISCOUNT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_COUPON_DISCOUNT" ADD CONSTRAINT "FK3A1F32071DF2D7F1" FOREIGN KEY ("TICKET_ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."KITCHEN_TICKET" ADD CONSTRAINT "FK341CBC275CF1375F" FOREIGN KEY ("PG_ID") REFERENCES "APP"."PRINTER_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ITEM_ORDER_TYPE" ADD CONSTRAINT "FKE2B8465789FE23F0" FOREIGN KEY ("MENU_ITEM_ID") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ITEM_ORDER_TYPE" ADD CONSTRAINT "FKE2B846573AC1D2E0" FOREIGN KEY ("ORDER_TYPE_ID") REFERENCES "APP"."ORDER_TYPE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DELIVERY_ADDRESS" ADD CONSTRAINT "FK29ACA6899E1C3CF1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "APP"."CUSTOMER" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM_PROPERTIES" ADD CONSTRAINT "FKF94186FF89FE23F0" FOREIGN KEY ("MENU_ITEM_ID") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_DISCOUNT" ADD CONSTRAINT "FK3DF5D4FAB9276E77" FOREIGN KEY ("TICKET_ITEMID") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TERMINAL_PRINTERS" ADD CONSTRAINT "FK99EDE5FCC433E65A" FOREIGN KEY ("VIRTUAL_PRINTER_ID") REFERENCES "APP"."VIRTUAL_PRINTER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TERMINAL_PRINTERS" ADD CONSTRAINT "FK99EDE5FC2AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM" ADD CONSTRAINT "FK979F546633E5D3B2" FOREIGN KEY ("SIZE_MODIFIER_ID") REFERENCES "APP"."TICKET_ITEM_MODIFIER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM" ADD CONSTRAINT "FK979F54665CF1375F" FOREIGN KEY ("PG_ID") REFERENCES "APP"."PRINTER_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM" ADD CONSTRAINT "FK979F54661DF2D7F1" FOREIGN KEY ("TICKET_ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ATTENDENCE_HISTORY" ADD CONSTRAINT "FKDFE829A3E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ATTENDENCE_HISTORY" ADD CONSTRAINT "FKDFE829A7660A5E3" FOREIGN KEY ("SHIFT_ID") REFERENCES "APP"."SHIFT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ATTENDENCE_HISTORY" ADD CONSTRAINT "FKDFE829A2AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."GRATUITY" ADD CONSTRAINT "FK34E4E377AA075D69" FOREIGN KEY ("OWNER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."GRATUITY" ADD CONSTRAINT "FK34E4E3771DF2D7F1" FOREIGN KEY ("TICKET_ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."GRATUITY" ADD CONSTRAINT "FK34E4E3772AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_TRANSACTION" ADD CONSTRAINT "FKAF48F43BFF3F328A" FOREIGN KEY ("FROM_WAREHOUSE_ID") REFERENCES "APP"."INVENTORY_WAREHOUSE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_TRANSACTION" ADD CONSTRAINT "FKAF48F43B5B397C5" FOREIGN KEY ("REFERENCE_ID") REFERENCES "APP"."PURCHASE_ORDER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_TRANSACTION" ADD CONSTRAINT "FKAF48F43B96A3D6BF" FOREIGN KEY ("ITEM_ID") REFERENCES "APP"."INVENTORY_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_TRANSACTION" ADD CONSTRAINT "FKAF48F43BEDA09759" FOREIGN KEY ("TO_WAREHOUSE_ID") REFERENCES "APP"."INVENTORY_WAREHOUSE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_TRANSACTION" ADD CONSTRAINT "FKAF48F43BD152C95F" FOREIGN KEY ("VENDOR_ID") REFERENCES "APP"."INVENTORY_VENDOR" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM" ADD CONSTRAINT "FK4CD5A1F35188AA24" FOREIGN KEY ("GROUP_ID") REFERENCES "APP"."MENU_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM" ADD CONSTRAINT "FK4CD5A1F3F3B77C57" FOREIGN KEY ("RECEPIE") REFERENCES "APP"."RECEPIE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM" ADD CONSTRAINT "FK4CD5A1F35CF1375F" FOREIGN KEY ("PG_ID") REFERENCES "APP"."PRINTER_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM" ADD CONSTRAINT "FK4CD5A1F3A4802F83" FOREIGN KEY ("TAX_ID") REFERENCES "APP"."TAX" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_COOKING_INSTRUCTION" ADD CONSTRAINT "FK3825F9D0DEC6120A" FOREIGN KEY ("TICKET_ITEM_ID") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_MODIFIER" ADD CONSTRAINT "FK59B6B1B75E0C7B8D" FOREIGN KEY ("GROUP_ID") REFERENCES "APP"."MENU_MODIFIER_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_MODIFIER" ADD CONSTRAINT "FK59B6B1B7A4802F83" FOREIGN KEY ("TAX_ID") REFERENCES "APP"."TAX" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ACTION_HISTORY" ADD CONSTRAINT "FK3F3AF36B3E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TABLE_TYPE_RELATION" ADD CONSTRAINT "FK93802290F5D6E47B" FOREIGN KEY ("TYPE_ID") REFERENCES "APP"."SHOP_TABLE_TYPE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TABLE_TYPE_RELATION" ADD CONSTRAINT "FK93802290DC46948D" FOREIGN KEY ("TABLE_ID") REFERENCES "APP"."SHOP_TABLE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DRAWER_PULL_REPORT_VOIDTICKETS" ADD CONSTRAINT "FK98CF9B143EF4CD9B" FOREIGN KEY ("DPREPORT_ID") REFERENCES "APP"."DRAWER_PULL_REPORT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "FK937B5F0CF575C7D4" FOREIGN KEY ("DRIVER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "FK937B5F0CAA075D69" FOREIGN KEY ("OWNER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "FK937B5F0C7660A5E3" FOREIGN KEY ("SHIFT_ID") REFERENCES "APP"."SHIFT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "FK937B5F0CC188EA51" FOREIGN KEY ("GRATUITY_ID") REFERENCES "APP"."GRATUITY" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "FK937B5F0C1F6A9A4A" FOREIGN KEY ("VOID_BY_USER") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET" ADD CONSTRAINT "FK937B5F0C2AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TABLE_BOOKING_INFO" ADD CONSTRAINT "FK301C4DE53E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TABLE_BOOKING_INFO" ADD CONSTRAINT "FK301C4DE59E1C3CF1" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "APP"."CUSTOMER" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_LOCATION" ADD CONSTRAINT "FK59073B58C46A9C15" FOREIGN KEY ("WAREHOUSE_ID") REFERENCES "APP"."INVENTORY_WAREHOUSE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."RECEPIE_ITEM" ADD CONSTRAINT "FK855626DBCAE89B83" FOREIGN KEY ("RECEPIE_ID") REFERENCES "APP"."RECEPIE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."RECEPIE_ITEM" ADD CONSTRAINT "FK855626DB1682B10E" FOREIGN KEY ("INVENTORY_ITEM") REFERENCES "APP"."INVENTORY_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."CUSTOMER_PROPERTIES" ADD CONSTRAINT "FKD43068347BBCCF0" FOREIGN KEY ("ID") REFERENCES "APP"."CUSTOMER" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PIZZA_PRICE" ADD CONSTRAINT "FKEAC11292DD545B77" FOREIGN KEY ("MENU_ITEM_SIZE") REFERENCES "APP"."MENU_ITEM_SIZE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PIZZA_PRICE" ADD CONSTRAINT "FKEAC11292A56D141C" FOREIGN KEY ("ORDER_TYPE") REFERENCES "APP"."ORDER_TYPE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PIZZA_PRICE" ADD CONSTRAINT "FKEAC112927C59441D" FOREIGN KEY ("CRUST") REFERENCES "APP"."PIZZA_CRUST" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM_TERMINAL_REF" ADD CONSTRAINT "FK9EA1AFC89FE23F0" FOREIGN KEY ("MENU_ITEM_ID") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_ITEM_TERMINAL_REF" ADD CONSTRAINT "FK9EA1AFC2AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."RECEPIE" ADD CONSTRAINT "FK6B4E177764931EFC" FOREIGN KEY ("MENU_ITEM") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_MODIFIER_RELATION" ADD CONSTRAINT "FK5D3F9ACBDEC6120A" FOREIGN KEY ("TICKET_ITEM_ID") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_MODIFIER_RELATION" ADD CONSTRAINT "FK5D3F9ACB6C108EF0" FOREIGN KEY ("MODIFIER_ID") REFERENCES "APP"."TICKET_ITEM_MODIFIER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_DISCOUNT" ADD CONSTRAINT "FK1FA465141DF2D7F1" FOREIGN KEY ("TICKET_ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_ITEM" ADD CONSTRAINT "FK7DC968369E60C333" FOREIGN KEY ("ITEM_VENDOR_ID") REFERENCES "APP"."INVENTORY_VENDOR" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_ITEM" ADD CONSTRAINT "FK7DC968366848D615" FOREIGN KEY ("RECIPE_UNIT_ID") REFERENCES "APP"."PACKAGING_UNIT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_ITEM" ADD CONSTRAINT "FK7DC968362CD583C1" FOREIGN KEY ("ITEM_GROUP_ID") REFERENCES "APP"."INVENTORY_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_ITEM" ADD CONSTRAINT "FK7DC968363525E956" FOREIGN KEY ("PUNIT_ID") REFERENCES "APP"."PACKAGING_UNIT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVENTORY_ITEM" ADD CONSTRAINT "FK7DC9683695E455D3" FOREIGN KEY ("ITEM_LOCATION_ID") REFERENCES "APP"."INVENTORY_LOCATION" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUGROUP_DISCOUNT" ADD CONSTRAINT "FKE3790E40113BF083" FOREIGN KEY ("MENUGROUP_ID") REFERENCES "APP"."MENU_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUGROUP_DISCOUNT" ADD CONSTRAINT "FKE3790E40D3E91E11" FOREIGN KEY ("DISCOUNT_ID") REFERENCES "APP"."COUPON_AND_DISCOUNT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."SHOP_TABLE" ADD CONSTRAINT "FK2458E9258979C3CD" FOREIGN KEY ("FLOOR_ID") REFERENCES "APP"."SHOP_FLOOR" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."KITCHEN_TICKET_ITEM" ADD CONSTRAINT "FK1462F02BCB07FAA3" FOREIGN KEY ("KITHEN_TICKET_ID") REFERENCES "APP"."KITCHEN_TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_MODIFIER_PROPERTIES" ADD CONSTRAINT "FK1273B4BBB79C6270" FOREIGN KEY ("MENU_MODIFIER_ID") REFERENCES "APP"."MENU_MODIFIER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."CASH_DRAWER" ADD CONSTRAINT "FK6221077D2AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "FK4D495E87660A5E3" FOREIGN KEY ("SHIFT_ID") REFERENCES "APP"."SHIFT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "FK4D495E8D9409968" FOREIGN KEY ("CURRENTTERMINAL") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "FK4D495E8897B1E39" FOREIGN KEY ("N_USER_TYPE") REFERENCES "APP"."USER_TYPE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "FKFE9871553E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "FKFE987155FC697D9E" FOREIGN KEY ("PAYOUT_REASON_ID") REFERENCES "APP"."PAYOUT_REASONS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "FKFE987155CA43B6" FOREIGN KEY ("PAYOUT_RECEPIENT_ID") REFERENCES "APP"."PAYOUT_RECEPIENTS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "FKFE9871551DF2D7F1" FOREIGN KEY ("TICKET_ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "FKFE9871552AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."CURRENCY_BALANCE" ADD CONSTRAINT "FK2CC0E08EFB910735" FOREIGN KEY ("DPR_ID") REFERENCES "APP"."DRAWER_PULL_REPORT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."CURRENCY_BALANCE" ADD CONSTRAINT "FK2CC0E08E9006558" FOREIGN KEY ("CASH_DRAWER_ID") REFERENCES "APP"."CASH_DRAWER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."CURRENCY_BALANCE" ADD CONSTRAINT "FK2CC0E08E28DD6C11" FOREIGN KEY ("CURRENCY_ID") REFERENCES "APP"."CURRENCY" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."SHOP_FLOOR_TEMPLATE_PROPERTIES" ADD CONSTRAINT "FKD70C313CA36AB054" FOREIGN KEY ("ID") REFERENCES "APP"."SHOP_FLOOR_TEMPLATE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PRINTER_GROUP_PRINTERS" ADD CONSTRAINT "FKC05B805E5F31265C" FOREIGN KEY ("PRINTER_ID") REFERENCES "APP"."PRINTER_GROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DRAWER_PULL_REPORT" ADD CONSTRAINT "FKAEC362203E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DRAWER_PULL_REPORT" ADD CONSTRAINT "FKAEC362202AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."SHOP_FLOOR_TEMPLATE" ADD CONSTRAINT "FKBA6EFBD68979C3CD" FOREIGN KEY ("FLOOR_ID") REFERENCES "APP"."SHOP_FLOOR" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."KIT_TICKET_TABLE_NUM" ADD CONSTRAINT "FK5696584BB73E273E" FOREIGN KEY ("KIT_TICKET_ID") REFERENCES "APP"."KITCHEN_TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUITEM_SHIFT" ADD CONSTRAINT "FKE03C92D533662891" FOREIGN KEY ("MENUITEM_ID") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUITEM_SHIFT" ADD CONSTRAINT "FKE03C92D57660A5E3" FOREIGN KEY ("SHIFT_ID") REFERENCES "APP"."SHIFT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TERMINAL" ADD CONSTRAINT "FKE83D827C969C6DE" FOREIGN KEY ("ASSIGNED_USER") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DRAWER_ASSIGNED_HISTORY" ADD CONSTRAINT "FK5A823C91F1DD782B" FOREIGN KEY ("A_USER") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_ADDON_RELATION" ADD CONSTRAINT "FK9F199634DEC6120A" FOREIGN KEY ("TICKET_ITEM_ID") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_ADDON_RELATION" ADD CONSTRAINT "FK9F1996346C108EF0" FOREIGN KEY ("MODIFIER_ID") REFERENCES "APP"."TICKET_ITEM_MODIFIER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU_GROUP" ADD CONSTRAINT "FK4DC1AB7F2E347FF0" FOREIGN KEY ("CATEGORY_ID") REFERENCES "APP"."MENU_CATEGORY" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USER_USER_PERMISSION" ADD CONSTRAINT "FK2DBEAA4F283ECC6" FOREIGN KEY ("PERMISSIONID") REFERENCES "APP"."USER_TYPE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USER_USER_PERMISSION" ADD CONSTRAINT "FK2DBEAA4F8F23F5E" FOREIGN KEY ("ELT") REFERENCES "APP"."USER_PERMISSION" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKETITEM_MODIFIERGROUP" ADD CONSTRAINT "FK21D455C8DC1B1BB1" FOREIGN KEY ("TICKETITEM_ID") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKETITEM_MODIFIERGROUP" ADD CONSTRAINT "FK21D455C874D5923A" FOREIGN KEY ("GROUP_ID") REFERENCES "APP"."MENUITEM_MODIFIERGROUP" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKETITEM_MODIFIERGROUP" ADD CONSTRAINT "FK21D455C8A73C1B20" FOREIGN KEY ("PARENT") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."EMPLOYEE_IN_OUT_HISTORY" ADD CONSTRAINT "FK6D5DB9FA3E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."EMPLOYEE_IN_OUT_HISTORY" ADD CONSTRAINT "FK6D5DB9FA7660A5E3" FOREIGN KEY ("SHIFT_ID") REFERENCES "APP"."SHIFT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."EMPLOYEE_IN_OUT_HISTORY" ADD CONSTRAINT "FK6D5DB9FA2AD2D031" FOREIGN KEY ("TERMINAL_ID") REFERENCES "APP"."TERMINAL" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TABLE_BOOKING_MAPPING" ADD CONSTRAINT "FK6BC51417160DE3B1" FOREIGN KEY ("BOOKING_ID") REFERENCES "APP"."TABLE_BOOKING_INFO" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TABLE_BOOKING_MAPPING" ADD CONSTRAINT "FK6BC51417DC46948D" FOREIGN KEY ("TABLE_ID") REFERENCES "APP"."SHOP_TABLE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DELIVERY_INSTRUCTION" ADD CONSTRAINT "FK29D9CA39E1C3D97" FOREIGN KEY ("CUSTOMER_NO") REFERENCES "APP"."CUSTOMER" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_PROPERTIES" ADD CONSTRAINT "FK70ECD046223049DE" FOREIGN KEY ("ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_TABLE_NUM" ADD CONSTRAINT "FK65AF15E21DF2D7F1" FOREIGN KEY ("TICKET_ID") REFERENCES "APP"."TICKET" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUMODIFIER_PIZZAMODIFIERPRICE" ADD CONSTRAINT "FK572726F374BE2C71" FOREIGN KEY ("PIZZAMODIFIERPRICE_ID") REFERENCES "APP"."PIZZA_MODIFIER_PRICE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUMODIFIER_PIZZAMODIFIERPRICE" ADD CONSTRAINT "FK572726F3AE3F2E91" FOREIGN KEY ("MENUMODIFIER_ID") REFERENCES "APP"."MENU_MODIFIER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUITEM_DISCOUNT" ADD CONSTRAINT "FKD89CCDEE33662891" FOREIGN KEY ("MENUITEM_ID") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUITEM_DISCOUNT" ADD CONSTRAINT "FKD89CCDEED3E91E11" FOREIGN KEY ("DISCOUNT_ID") REFERENCES "APP"."COUPON_AND_DISCOUNT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."CASH_DRAWER_RESET_HISTORY" ADD CONSTRAINT "FK719418223E20AD51" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("AUTO_ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MODIFIER_MULTIPLIER_PRICE" ADD CONSTRAINT "FK8A1609939C9E4883" FOREIGN KEY ("PIZZA_MODIFIER_PRICE_ID") REFERENCES "APP"."PIZZA_MODIFIER_PRICE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MODIFIER_MULTIPLIER_PRICE" ADD CONSTRAINT "FK8A160993AE3F2E91" FOREIGN KEY ("MENUMODIFIER_ID") REFERENCES "APP"."MENU_MODIFIER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MODIFIER_MULTIPLIER_PRICE" ADD CONSTRAINT "FK8A16099391D62C51" FOREIGN KEY ("MULTIPLIER_ID") REFERENCES "APP"."MULTIPLIER" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PIZZA_MODIFIER_PRICE" ADD CONSTRAINT "FKD3DE7E7896183657" FOREIGN KEY ("ITEM_SIZE") REFERENCES "APP"."MENU_ITEM_SIZE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSACTION_PROPERTIES" ADD CONSTRAINT "FKE3DE65548E8203BC" FOREIGN KEY ("ID") REFERENCES "APP"."TRANSACTIONS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."VIRTUALPRINTER_ORDER_TYPE" ADD CONSTRAINT "FK9AF7853BCF15F4A6" FOREIGN KEY ("PRINTER_ID") REFERENCES "APP"."VIRTUAL_PRINTER" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUITEM_PIZZAPIRCE" ADD CONSTRAINT "FK17BD51A089FE23F0" FOREIGN KEY ("MENU_ITEM_ID") REFERENCES "APP"."MENU_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENUITEM_PIZZAPIRCE" ADD CONSTRAINT "FK17BD51A0AE5D580" FOREIGN KEY ("PIZZA_PRICE_ID") REFERENCES "APP"."PIZZA_PRICE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TICKET_ITEM_MODIFIER" ADD CONSTRAINT "FK8FD6290DEC6120A" FOREIGN KEY ("TICKET_ITEM_ID") REFERENCES "APP"."TICKET_ITEM" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

